language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: YacWee//5E1lh6x5CPx5EHmE0d+CTMFWz7vOiQigAr/L0rAerxWneBulpRO8hw7F6vGJopC4197QJrff8KoVbCElEOq1yLeokvWnVY+7xtmKp/hhXxtJrF8120wKObI0/LVZ3NuSwSY/WXccn93Yhzf9N0xQXD8SKv26v1ck7oA=
